config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all if user.nil?

    return if user.nil?

    can :manage, :all if user.role == 'admin'
    can :read, :all if user.role == 'user'
    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comments_counter
  before_destroy :update_comments_down

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end

  def update_comments_down
    post.update_columns('comments_counter' => post.comments_counter - 1)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', autosave: true
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_post_counter
  before_destroy :update_posts_down

  validates :title, presence: true, allow_blank: false, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def update_post_counter
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.order(created_at: :desc).includes([:author]).limit(5)
  end

  def update_posts_down
    author.update_columns('posts_counter' => author.posts_counter - 1)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true, allow_blank: false
  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up,
      keys: %i[name email bio password password_confirmation]
    )
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @user = current_user
  end

  def create
    post = Post.find(params[:post_id])
    @comment = Comment.new(post_params(post))

    if @comment.save
      flash[:notice] = 'Comment created successfully!'
      redirect_to user_post_path(current_user, post)
    else
      flash[:alert] = 'Can not add a comment.'
      redirect_to { new_user_post(current_user) }
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to { user_posts(current_user) }
  end

  private

  def post_params(post)
    a_post = params.require(:comment).permit(:text)
    a_post[:author] = current_user
    a_post[:post] = post
    a_post
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    post = Post.find(params[:post_id])
    @like = Like.new(author: current_user, post:)

    if @like.save
      flash[:notice] = 'You have successfully liked the post.'
      redirect_to user_post_path(current_user, post)
    else
      flash[:alert] = 'Can not like'
      redirect_to { new_user_post(current_user) }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def new
    @post = Post.new
    @user = User.find(params[:user_id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      flash[:notice] = 'New post created successfully!'
      redirect_to { user_posts(current_user) }
    else
      flash[:alert] = 'Can not add a new post.'
      redirect_to { new_user_post(current_user) }
    end
  end

  def show
    @post = Post.includes(:comments).find(params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_path(params[:user_id])
  end

  private

  def post_params
    a_post = params.require(:post).permit(:title, :text)
    a_post[:author] = current_user
    a_post
  end

  def post_params_setup
    Post.create(author: current_user, title: params[:post][:title], text: params[:post][:text])
  end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      raise e if get?

      if has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :config_sign_up_params, only: [:create]

  protected

  def config_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="mt-5 d-flex column justify-content-center align-items-center">
  <h2>Add New Comment</h2>

  <%= form_with(model: @comment, url: user_post_comments_path) do |f| %>
    <div>
      <%= f.text_area :text, placeholder: "Type your comment here" %>
    </div>
    
    <%= f.submit 'New Comment', class: 'mt-3 pagination text-center' %>
  <% end %>
</div>

app/views/layouts/_flash-messages.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <div class="alert-<%= type %>">
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header class="header px-5 mt-3">
  <div class="logo fs-2 fw-bolder"><%= link_to "Blog App", root_path, class: 'link' %></div>
  <nav class="navbar">
    <ul class="nav-list d-flex">
      <% if user_signed_in? %>
      <li class="nav-item px-2"><%= link_to "Home", root_path %></li>
      <li class="nav-item px-3 signout-btn">
        <%= button_to "Sign out", destroy_user_session_path, method: :delete,
        class: 'clickable link' %>
      </li>
      <% else %>
      <li class="nav-item px-3">
        <%= link_to "Log in", new_user_session_path, class: 'link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: 'link' %>
      </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
      rel="stylesheet" 
    >

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <main class="blog-container">
      <%= render "layouts/flash-messages" %>

      <%= yield %>
    </main>
    
  </body>
</html>

app/views/likes/new.html.erb
<h2>Add New Like</h2>

<%= form_with(model: @like, url: user_post_likes_path) do |f| %>
  <%= f.submit 'Add New Like' %>
<% end %>

app/views/posts/_comment.html.erb
<div class="user-bloc-post-comments">
  <% comments.includes([:author]).each do |comment| %>
    <span><%= comment.author.name %>: <%= comment.text %></span>

    <% if can? :destroy, comment %>
           <%= button_to "Delete Comment", user_post_comment_path(post.author, post, comment), method: :delete, class: 'pagination' %>
        <% end %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="user-bloc-posts">
  <div class="user-bloc-post">
    <%= link_to user_post_path(user, post) do %>
      <h4><%= post.title %></h4>
    <% end %>
    <span class="user-post-content"><%= post.text %></span>
    <span class="comments-likes">Comments: <%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %></span>
  </div>

  <% unless post.comments_counter == 0 %>
    <%= render partial: 'comment', locals: { post: post, comments: post.recent_comments } %>
  <% else %>
    <div class="user-bloc-post-comments mt-2 text-center">
      <span><%= 'No comment available from this post! Click the Post title to add anew one' %></span>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="posts-bloc">
  <div class="user-bloc" id="user_<%= @user.id %>">
    <div class="user-image">
      <img src="<%= @user.photo %>" alt="user image">
    </div>
    <div class="user-data">
      <h2><%= @user.name%></h2>
      <span class="user-posts">Number of posts: <%= @user.posts_counter%></span>
    </div>
  </div>

  <% @posts.each do |post| %>
      <%= render partial: "post", locals: { post: post, user: @user } %>
  <% end %>

  <div class="d-flex">
    <button class="pagination clickable mx-2">Pagination</button>
  
    <% if current_user %>
      <%= button_to 'Add New Post', new_user_post_path(@user), method: :get, class: "clickable pagination mx-2" %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="mt-5">
  <%= form_with(model: @post, url: [@user, @post]) do |form| %>
    <div>
      <%= form.text_field :title, placeholder: 'Enter post title' %>  
    </div>
    
    <div class="mt-2">
      <%= form.text_area :text, placeholder: 'Enter post text' %>  
    </div>
    
    <%= form.submit "Add new post", class: 'pagination text-center' %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="posts-bloc">
  <div class="user-bloc-posts">
    <div class="user-bloc-post">
      <h4><%= @post.title %></h4>
      <span class="user-post-content-comments">Comments: <%= @post.comments_counter || 0 %>, Likes: <%= @post.likes_counter || 0 %></span>
      <span class="user-post-content"><%= @post.text %></span>
    </div>
    
    <% unless @post.comments_counter == 0 %>
      <%= render partial: 'comment', locals: { post: @post, comments: @post.comments }%>
    <% else %>
      <div class="user-bloc-post-comments mt-2">
        <span><%= 'No comment available from this post! Add a new one from buttons below.' %></span>
      </div>
    <% end %>
  </div>

  <div class="d-flex">
    <% if current_user %>
      <%= button_to "New Comment", new_user_post_comment_path(@post.author, @post), method: :get, class: "pagination clickable" %>
    
      <%= button_to "Like", user_post_likes_path(@post.author, @post), class: "pagination clickable mx-4 px-4" %>
    <% end %>

    <% if can? :destroy, @post %>
      <%= button_to "Delete Post" ,[@post.author, @post], method: :delete, class: "pagination" %>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div class="user-bloc" id="user_<%= user.id %>">
  <div class="user-image">
    <img src="<%= user.photo %>" alt="user image">
  </div>
  <div class="user-data">
    <h4 class="title"><%= link_to user.name, user_path(user) %></h4>
    <span class="user-posts">Number of posts: <%= user.posts_counter || 0 %></span>
  </div>
</div>

app/views/users/index.html.erb
<div class="users-bloc">
  <% @users.each do |user| %>
    <%= render partial: 'user', locals: {user: user} %>
  <% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'signup-width-fields text-center link pagination mt-2' %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: 'fs-5 blue-link-color' %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="users-bloc" id="user_<%= @user.id %>">
  <div class="user-bloc">
    <div class="user-image">
      <img src="<%= @user.photo %>" alt="user image">
    </div>
    <div class="user-data">
      <h4 class="user-name"><%= @user.name %></h4>
      <span class="user-posts">Number of posts: <%= @user.posts_counter || 0 %></span>
    </div>
  </div>
  <div class="user-bio">
    <h4>Bio</h4>
    <span class="user-bio-content"><%= @user.bio %></span>
  </div>
  <div class="user-bloc-posts">
    <% @user.recent_posts.each do |post| %>
    <div class="user-bloc-post">
      <%= link_to user_post_path(@user, post) do %>
        <h4><%= post.title %></h4>
      <% end %>
      <span class="user-post-content"><%= post.text %></span>
      <span class="user-post-content-comments">Comment: <%= post.comments_counter || 0 %>, Likes : <%= post.likes_counter || 0 %></span>
    </div>
    <% end %>
  </div>
  <button class="see-posts clickable">
    <%= link_to 'See All Posts', user_posts_path(@user) %>
  </button>
</div>